/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ConditionsRouteImport } from './routes/conditions'
import { Route as ConfidentialiteRouteImport } from './routes/confidentialite'
import { Route as DevenirProfesseurRouteImport } from './routes/devenir-professeur'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as PublierRouteImport } from './routes/publier'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as VerifierEmailRouteImport } from './routes/verifier-email'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as LangIndexRouteImport } from './routes/$lang.index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCompteRouteImport } from './routes/_authenticated/compte'
import { Route as AuthenticatedMessagesRouteImport } from './routes/_authenticated/messages'
import { Route as AuthenticatedMonBesoinRouteImport } from './routes/_authenticated/mon-besoin'
import { Route as AvisTokenRouteImport } from './routes/avis.$token'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as ProfesseursIndexRouteImport } from './routes/professeurs.index'
import { Route as ProfesseursIdRouteImport } from './routes/professeurs.$id'
import { Route as LangProfesseurSlugRouteImport } from './routes/$lang.professeur.$slug'
import { Route as LangProfesseursIndexRouteImport } from './routes/$lang.professeurs.index'
import { Route as AuthenticatedDemandesIndexRouteImport } from './routes/_authenticated/demandes.index'
import { Route as AuthenticatedDemandesIdRouteImport } from './routes/_authenticated/demandes.$id'
import { Route as AuthenticatedProIndexRouteImport } from './routes/_authenticated/pro.index'
import { Route as AuthenticatedProDemandesRouteImport } from './routes/_authenticated/pro.demandes'
import { Route as AuthenticatedProInscriptionRouteImport } from './routes/_authenticated/pro.inscription'
import { Route as ArBlogIndexRouteImport } from './routes/ar.blog.index'
import { Route as ArBlogSlugRouteImport } from './routes/ar.blog.$slug'
import { Route as FrBlogIndexRouteImport } from './routes/fr.blog.index'
import { Route as FrBlogSlugRouteImport } from './routes/fr.blog.$slug'
import { Route as LangProfesseursVilleIndexRouteImport } from './routes/$lang.professeurs.$ville.index'
import { Route as ApiPublicCronExpireLaunchOffersRouteImport } from './routes/api/public/cron/expire-launch-offers'
import { Route as LangProfesseursVilleMatiereIndexRouteImport } from './routes/$lang.professeurs.$ville.$matiere.index'
import { Route as LangProfesseursVilleMatiereNiveauRouteImport } from './routes/$lang.professeurs.$ville.$matiere.$niveau'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsRoute = ConditionsRouteImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfidentialiteRoute = ConfidentialiteRouteImport.update({
  id: '/confidentialite',
  path: '/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const DevenirProfesseurRoute = DevenirProfesseurRouteImport.update({
  id: '/devenir-professeur',
  path: '/devenir-professeur',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const PublierRoute = PublierRouteImport.update({
  id: '/publier',
  path: '/publier',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierEmailRoute = VerifierEmailRouteImport.update({
  id: '/verifier-email',
  path: '/verifier-email',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompteRoute = AuthenticatedCompteRouteImport.update({
  id: '/compte',
  path: '/compte',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMessagesRoute = AuthenticatedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonBesoinRoute = AuthenticatedMonBesoinRouteImport.update({
  id: '/mon-besoin',
  path: '/mon-besoin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AvisTokenRoute = AvisTokenRouteImport.update({
  id: '/avis/$token',
  path: '/avis/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursIndexRoute = ProfesseursIndexRouteImport.update({
  id: '/professeurs/',
  path: '/professeurs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursIdRoute = ProfesseursIdRouteImport.update({
  id: '/professeurs/$id',
  path: '/professeurs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LangProfesseurSlugRoute = LangProfesseurSlugRouteImport.update({
  id: '/professeur/$slug',
  path: '/professeur/$slug',
  getParentRoute: () => LangRoute,
} as any)
const LangProfesseursIndexRoute = LangProfesseursIndexRouteImport.update({
  id: '/professeurs/',
  path: '/professeurs/',
  getParentRoute: () => LangRoute,
} as any)
const AuthenticatedDemandesIndexRoute =
  AuthenticatedDemandesIndexRouteImport.update({
    id: '/demandes/',
    path: '/demandes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDemandesIdRoute = AuthenticatedDemandesIdRouteImport.update({
  id: '/demandes/$id',
  path: '/demandes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProIndexRoute = AuthenticatedProIndexRouteImport.update({
  id: '/pro/',
  path: '/pro/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProDemandesRoute =
  AuthenticatedProDemandesRouteImport.update({
    id: '/pro/demandes',
    path: '/pro/demandes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProInscriptionRoute =
  AuthenticatedProInscriptionRouteImport.update({
    id: '/pro/inscription',
    path: '/pro/inscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ArBlogIndexRoute = ArBlogIndexRouteImport.update({
  id: '/ar/blog/',
  path: '/ar/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArBlogSlugRoute = ArBlogSlugRouteImport.update({
  id: '/ar/blog/$slug',
  path: '/ar/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBlogIndexRoute = FrBlogIndexRouteImport.update({
  id: '/fr/blog/',
  path: '/fr/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const FrBlogSlugRoute = FrBlogSlugRouteImport.update({
  id: '/fr/blog/$slug',
  path: '/fr/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LangProfesseursVilleIndexRoute =
  LangProfesseursVilleIndexRouteImport.update({
    id: '/professeurs/$ville/',
    path: '/professeurs/$ville/',
    getParentRoute: () => LangRoute,
  } as any)
const ApiPublicCronExpireLaunchOffersRoute =
  ApiPublicCronExpireLaunchOffersRouteImport.update({
    id: '/api/public/cron/expire-launch-offers',
    path: '/api/public/cron/expire-launch-offers',
    getParentRoute: () => rootRouteImport,
  } as any)
const LangProfesseursVilleMatiereIndexRoute =
  LangProfesseursVilleMatiereIndexRouteImport.update({
    id: '/professeurs/$ville/$matiere/',
    path: '/professeurs/$ville/$matiere/',
    getParentRoute: () => LangRoute,
  } as any)
const LangProfesseursVilleMatiereNiveauRoute =
  LangProfesseursVilleMatiereNiveauRouteImport.update({
    id: '/professeurs/$ville/$matiere/$niveau',
    path: '/professeurs/$ville/$matiere/$niveau',
    getParentRoute: () => LangRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/auth': typeof AuthRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/devenir-professeur': typeof DevenirProfesseurRoute
  '/inscription': typeof InscriptionRoute
  '/publier': typeof PublierRoute
  '/tarifs': typeof TarifsRoute
  '/verifier-email': typeof VerifierEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/mon-besoin': typeof AuthenticatedMonBesoinRoute
  '/avis/$token': typeof AvisTokenRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/$lang/': typeof LangIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/professeurs/': typeof ProfesseursIndexRoute
  '/$lang/professeur/$slug': typeof LangProfesseurSlugRoute
  '/demandes/$id': typeof AuthenticatedDemandesIdRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/inscription': typeof AuthenticatedProInscriptionRoute
  '/ar/blog/$slug': typeof ArBlogSlugRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/$lang/professeurs/': typeof LangProfesseursIndexRoute
  '/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/pro/': typeof AuthenticatedProIndexRoute
  '/ar/blog/': typeof ArBlogIndexRoute
  '/fr/blog/': typeof FrBlogIndexRoute
  '/api/public/cron/expire-launch-offers': typeof ApiPublicCronExpireLaunchOffersRoute
  '/$lang/professeurs/$ville/': typeof LangProfesseursVilleIndexRoute
  '/$lang/professeurs/$ville/$matiere/$niveau': typeof LangProfesseursVilleMatiereNiveauRoute
  '/$lang/professeurs/$ville/$matiere/': typeof LangProfesseursVilleMatiereIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/devenir-professeur': typeof DevenirProfesseurRoute
  '/inscription': typeof InscriptionRoute
  '/publier': typeof PublierRoute
  '/tarifs': typeof TarifsRoute
  '/verifier-email': typeof VerifierEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/compte': typeof AuthenticatedCompteRoute
  '/messages': typeof AuthenticatedMessagesRoute
  '/mon-besoin': typeof AuthenticatedMonBesoinRoute
  '/avis/$token': typeof AvisTokenRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/$lang': typeof LangIndexRoute
  '/blog': typeof BlogIndexRoute
  '/professeurs': typeof ProfesseursIndexRoute
  '/$lang/professeur/$slug': typeof LangProfesseurSlugRoute
  '/demandes/$id': typeof AuthenticatedDemandesIdRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/inscription': typeof AuthenticatedProInscriptionRoute
  '/ar/blog/$slug': typeof ArBlogSlugRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/$lang/professeurs': typeof LangProfesseursIndexRoute
  '/demandes': typeof AuthenticatedDemandesIndexRoute
  '/pro': typeof AuthenticatedProIndexRoute
  '/ar/blog': typeof ArBlogIndexRoute
  '/fr/blog': typeof FrBlogIndexRoute
  '/api/public/cron/expire-launch-offers': typeof ApiPublicCronExpireLaunchOffersRoute
  '/$lang/professeurs/$ville': typeof LangProfesseursVilleIndexRoute
  '/$lang/professeurs/$ville/$matiere/$niveau': typeof LangProfesseursVilleMatiereNiveauRoute
  '/$lang/professeurs/$ville/$matiere': typeof LangProfesseursVilleMatiereIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$lang': typeof LangRouteWithChildren
  '/auth': typeof AuthRoute
  '/conditions': typeof ConditionsRoute
  '/confidentialite': typeof ConfidentialiteRoute
  '/devenir-professeur': typeof DevenirProfesseurRoute
  '/inscription': typeof InscriptionRoute
  '/publier': typeof PublierRoute
  '/tarifs': typeof TarifsRoute
  '/verifier-email': typeof VerifierEmailRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/compte': typeof AuthenticatedCompteRoute
  '/_authenticated/messages': typeof AuthenticatedMessagesRoute
  '/_authenticated/mon-besoin': typeof AuthenticatedMonBesoinRoute
  '/avis/$token': typeof AvisTokenRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/professeurs/$id': typeof ProfesseursIdRoute
  '/$lang/': typeof LangIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/professeurs/': typeof ProfesseursIndexRoute
  '/$lang/professeur/$slug': typeof LangProfesseurSlugRoute
  '/_authenticated/demandes/$id': typeof AuthenticatedDemandesIdRoute
  '/_authenticated/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/_authenticated/pro/inscription': typeof AuthenticatedProInscriptionRoute
  '/ar/blog/$slug': typeof ArBlogSlugRoute
  '/fr/blog/$slug': typeof FrBlogSlugRoute
  '/$lang/professeurs/': typeof LangProfesseursIndexRoute
  '/_authenticated/demandes/': typeof AuthenticatedDemandesIndexRoute
  '/_authenticated/pro/': typeof AuthenticatedProIndexRoute
  '/ar/blog/': typeof ArBlogIndexRoute
  '/fr/blog/': typeof FrBlogIndexRoute
  '/api/public/cron/expire-launch-offers': typeof ApiPublicCronExpireLaunchOffersRoute
  '/$lang/professeurs/$ville/': typeof LangProfesseursVilleIndexRoute
  '/$lang/professeurs/$ville/$matiere/$niveau': typeof LangProfesseursVilleMatiereNiveauRoute
  '/$lang/professeurs/$ville/$matiere/': typeof LangProfesseursVilleMatiereIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/auth'
    | '/conditions'
    | '/confidentialite'
    | '/devenir-professeur'
    | '/inscription'
    | '/publier'
    | '/tarifs'
    | '/verifier-email'
    | '/verify-email'
    | '/admin'
    | '/compte'
    | '/messages'
    | '/mon-besoin'
    | '/avis/$token'
    | '/blog/$slug'
    | '/professeurs/$id'
    | '/$lang/'
    | '/blog/'
    | '/professeurs/'
    | '/$lang/professeur/$slug'
    | '/demandes/$id'
    | '/pro/demandes'
    | '/pro/inscription'
    | '/ar/blog/$slug'
    | '/fr/blog/$slug'
    | '/$lang/professeurs/'
    | '/demandes/'
    | '/pro/'
    | '/ar/blog/'
    | '/fr/blog/'
    | '/api/public/cron/expire-launch-offers'
    | '/$lang/professeurs/$ville/'
    | '/$lang/professeurs/$ville/$matiere/$niveau'
    | '/$lang/professeurs/$ville/$matiere/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conditions'
    | '/confidentialite'
    | '/devenir-professeur'
    | '/inscription'
    | '/publier'
    | '/tarifs'
    | '/verifier-email'
    | '/verify-email'
    | '/admin'
    | '/compte'
    | '/messages'
    | '/mon-besoin'
    | '/avis/$token'
    | '/blog/$slug'
    | '/professeurs/$id'
    | '/$lang'
    | '/blog'
    | '/professeurs'
    | '/$lang/professeur/$slug'
    | '/demandes/$id'
    | '/pro/demandes'
    | '/pro/inscription'
    | '/ar/blog/$slug'
    | '/fr/blog/$slug'
    | '/$lang/professeurs'
    | '/demandes'
    | '/pro'
    | '/ar/blog'
    | '/fr/blog'
    | '/api/public/cron/expire-launch-offers'
    | '/$lang/professeurs/$ville'
    | '/$lang/professeurs/$ville/$matiere/$niveau'
    | '/$lang/professeurs/$ville/$matiere'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$lang'
    | '/auth'
    | '/conditions'
    | '/confidentialite'
    | '/devenir-professeur'
    | '/inscription'
    | '/publier'
    | '/tarifs'
    | '/verifier-email'
    | '/verify-email'
    | '/_authenticated/admin'
    | '/_authenticated/compte'
    | '/_authenticated/messages'
    | '/_authenticated/mon-besoin'
    | '/avis/$token'
    | '/blog/$slug'
    | '/professeurs/$id'
    | '/$lang/'
    | '/blog/'
    | '/professeurs/'
    | '/$lang/professeur/$slug'
    | '/_authenticated/demandes/$id'
    | '/_authenticated/pro/demandes'
    | '/_authenticated/pro/inscription'
    | '/ar/blog/$slug'
    | '/fr/blog/$slug'
    | '/$lang/professeurs/'
    | '/_authenticated/demandes/'
    | '/_authenticated/pro/'
    | '/ar/blog/'
    | '/fr/blog/'
    | '/api/public/cron/expire-launch-offers'
    | '/$lang/professeurs/$ville/'
    | '/$lang/professeurs/$ville/$matiere/$niveau'
    | '/$lang/professeurs/$ville/$matiere/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LangRoute: typeof LangRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConditionsRoute: typeof ConditionsRoute
  ConfidentialiteRoute: typeof ConfidentialiteRoute
  DevenirProfesseurRoute: typeof DevenirProfesseurRoute
  InscriptionRoute: typeof InscriptionRoute
  PublierRoute: typeof PublierRoute
  TarifsRoute: typeof TarifsRoute
  VerifierEmailRoute: typeof VerifierEmailRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AvisTokenRoute: typeof AvisTokenRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ProfesseursIdRoute: typeof ProfesseursIdRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ProfesseursIndexRoute: typeof ProfesseursIndexRoute
  ArBlogSlugRoute: typeof ArBlogSlugRoute
  FrBlogSlugRoute: typeof FrBlogSlugRoute
  ArBlogIndexRoute: typeof ArBlogIndexRoute
  FrBlogIndexRoute: typeof FrBlogIndexRoute
  ApiPublicCronExpireLaunchOffersRoute: typeof ApiPublicCronExpireLaunchOffersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confidentialite': {
      id: '/confidentialite'
      path: '/confidentialite'
      fullPath: '/confidentialite'
      preLoaderRoute: typeof ConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devenir-professeur': {
      id: '/devenir-professeur'
      path: '/devenir-professeur'
      fullPath: '/devenir-professeur'
      preLoaderRoute: typeof DevenirProfesseurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publier': {
      id: '/publier'
      path: '/publier'
      fullPath: '/publier'
      preLoaderRoute: typeof PublierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier-email': {
      id: '/verifier-email'
      path: '/verifier-email'
      fullPath: '/verifier-email'
      preLoaderRoute: typeof VerifierEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compte': {
      id: '/_authenticated/compte'
      path: '/compte'
      fullPath: '/compte'
      preLoaderRoute: typeof AuthenticatedCompteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/messages': {
      id: '/_authenticated/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthenticatedMessagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mon-besoin': {
      id: '/_authenticated/mon-besoin'
      path: '/mon-besoin'
      fullPath: '/mon-besoin'
      preLoaderRoute: typeof AuthenticatedMonBesoinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/avis/$token': {
      id: '/avis/$token'
      path: '/avis/$token'
      fullPath: '/avis/$token'
      preLoaderRoute: typeof AvisTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs/': {
      id: '/professeurs/'
      path: '/professeurs'
      fullPath: '/professeurs/'
      preLoaderRoute: typeof ProfesseursIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs/$id': {
      id: '/professeurs/$id'
      path: '/professeurs/$id'
      fullPath: '/professeurs/$id'
      preLoaderRoute: typeof ProfesseursIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/professeur/$slug': {
      id: '/$lang/professeur/$slug'
      path: '/professeur/$slug'
      fullPath: '/$lang/professeur/$slug'
      preLoaderRoute: typeof LangProfesseurSlugRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/professeurs/': {
      id: '/$lang/professeurs/'
      path: '/professeurs'
      fullPath: '/$lang/professeurs/'
      preLoaderRoute: typeof LangProfesseursIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/_authenticated/demandes/': {
      id: '/_authenticated/demandes/'
      path: '/demandes'
      fullPath: '/demandes/'
      preLoaderRoute: typeof AuthenticatedDemandesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/demandes/$id': {
      id: '/_authenticated/demandes/$id'
      path: '/demandes/$id'
      fullPath: '/demandes/$id'
      preLoaderRoute: typeof AuthenticatedDemandesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/': {
      id: '/_authenticated/pro/'
      path: '/pro'
      fullPath: '/pro/'
      preLoaderRoute: typeof AuthenticatedProIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/demandes': {
      id: '/_authenticated/pro/demandes'
      path: '/pro/demandes'
      fullPath: '/pro/demandes'
      preLoaderRoute: typeof AuthenticatedProDemandesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro/inscription': {
      id: '/_authenticated/pro/inscription'
      path: '/pro/inscription'
      fullPath: '/pro/inscription'
      preLoaderRoute: typeof AuthenticatedProInscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/ar/blog/': {
      id: '/ar/blog/'
      path: '/ar/blog'
      fullPath: '/ar/blog/'
      preLoaderRoute: typeof ArBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ar/blog/$slug': {
      id: '/ar/blog/$slug'
      path: '/ar/blog/$slug'
      fullPath: '/ar/blog/$slug'
      preLoaderRoute: typeof ArBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/blog/': {
      id: '/fr/blog/'
      path: '/fr/blog'
      fullPath: '/fr/blog/'
      preLoaderRoute: typeof FrBlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fr/blog/$slug': {
      id: '/fr/blog/$slug'
      path: '/fr/blog/$slug'
      fullPath: '/fr/blog/$slug'
      preLoaderRoute: typeof FrBlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/professeurs/$ville/': {
      id: '/$lang/professeurs/$ville/'
      path: '/professeurs/$ville'
      fullPath: '/$lang/professeurs/$ville/'
      preLoaderRoute: typeof LangProfesseursVilleIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/api/public/cron/expire-launch-offers': {
      id: '/api/public/cron/expire-launch-offers'
      path: '/api/public/cron/expire-launch-offers'
      fullPath: '/api/public/cron/expire-launch-offers'
      preLoaderRoute: typeof ApiPublicCronExpireLaunchOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/professeurs/$ville/$matiere/': {
      id: '/$lang/professeurs/$ville/$matiere/'
      path: '/professeurs/$ville/$matiere'
      fullPath: '/$lang/professeurs/$ville/$matiere/'
      preLoaderRoute: typeof LangProfesseursVilleMatiereIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/professeurs/$ville/$matiere/$niveau': {
      id: '/$lang/professeurs/$ville/$matiere/$niveau'
      path: '/professeurs/$ville/$matiere/$niveau'
      fullPath: '/$lang/professeurs/$ville/$matiere/$niveau'
      preLoaderRoute: typeof LangProfesseursVilleMatiereNiveauRouteImport
      parentRoute: typeof LangRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCompteRoute: typeof AuthenticatedCompteRoute
  AuthenticatedMessagesRoute: typeof AuthenticatedMessagesRoute
  AuthenticatedMonBesoinRoute: typeof AuthenticatedMonBesoinRoute
  AuthenticatedDemandesIdRoute: typeof AuthenticatedDemandesIdRoute
  AuthenticatedProDemandesRoute: typeof AuthenticatedProDemandesRoute
  AuthenticatedProInscriptionRoute: typeof AuthenticatedProInscriptionRoute
  AuthenticatedDemandesIndexRoute: typeof AuthenticatedDemandesIndexRoute
  AuthenticatedProIndexRoute: typeof AuthenticatedProIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCompteRoute: AuthenticatedCompteRoute,
  AuthenticatedMessagesRoute: AuthenticatedMessagesRoute,
  AuthenticatedMonBesoinRoute: AuthenticatedMonBesoinRoute,
  AuthenticatedDemandesIdRoute: AuthenticatedDemandesIdRoute,
  AuthenticatedProDemandesRoute: AuthenticatedProDemandesRoute,
  AuthenticatedProInscriptionRoute: AuthenticatedProInscriptionRoute,
  AuthenticatedDemandesIndexRoute: AuthenticatedDemandesIndexRoute,
  AuthenticatedProIndexRoute: AuthenticatedProIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface LangRouteChildren {
  LangIndexRoute: typeof LangIndexRoute
  LangProfesseurSlugRoute: typeof LangProfesseurSlugRoute
  LangProfesseursIndexRoute: typeof LangProfesseursIndexRoute
  LangProfesseursVilleIndexRoute: typeof LangProfesseursVilleIndexRoute
  LangProfesseursVilleMatiereNiveauRoute: typeof LangProfesseursVilleMatiereNiveauRoute
  LangProfesseursVilleMatiereIndexRoute: typeof LangProfesseursVilleMatiereIndexRoute
}

const LangRouteChildren: LangRouteChildren = {
  LangIndexRoute: LangIndexRoute,
  LangProfesseurSlugRoute: LangProfesseurSlugRoute,
  LangProfesseursIndexRoute: LangProfesseursIndexRoute,
  LangProfesseursVilleIndexRoute: LangProfesseursVilleIndexRoute,
  LangProfesseursVilleMatiereNiveauRoute:
    LangProfesseursVilleMatiereNiveauRoute,
  LangProfesseursVilleMatiereIndexRoute: LangProfesseursVilleMatiereIndexRoute,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LangRoute: LangRouteWithChildren,
  AuthRoute: AuthRoute,
  ConditionsRoute: ConditionsRoute,
  ConfidentialiteRoute: ConfidentialiteRoute,
  DevenirProfesseurRoute: DevenirProfesseurRoute,
  InscriptionRoute: InscriptionRoute,
  PublierRoute: PublierRoute,
  TarifsRoute: TarifsRoute,
  VerifierEmailRoute: VerifierEmailRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AvisTokenRoute: AvisTokenRoute,
  BlogSlugRoute: BlogSlugRoute,
  ProfesseursIdRoute: ProfesseursIdRoute,
  BlogIndexRoute: BlogIndexRoute,
  ProfesseursIndexRoute: ProfesseursIndexRoute,
  ArBlogSlugRoute: ArBlogSlugRoute,
  FrBlogSlugRoute: FrBlogSlugRoute,
  ArBlogIndexRoute: ArBlogIndexRoute,
  FrBlogIndexRoute: FrBlogIndexRoute,
  ApiPublicCronExpireLaunchOffersRoute: ApiPublicCronExpireLaunchOffersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
